# MSB7211 Big Bio-data analysis assignment
#### Student name: Yiga Fahim
#### Reg No: 2022/HD07/2054U
#### Date: 29-MAR-2023

### **Qn1**. What is NumPy, and what are some of its key features?

### **Ans.** 
NumPy (Numerical Python) is a popular Python library that provides support for numerical operations on multi-dimensional arrays and matrices. It is used for scientific computing, data analysis, and machine learning applications.

### Key features
1. Multi-dimensional arrays: NumPy provides a powerful and efficient array object, called ndarray, which can be used to store and manipulate multi-dimensional data. Ndarrays can be used to represent vectors, matrices, and tensors of various dimensions.

2. Broadcasting: NumPy allows for element-wise operations between arrays of different shapes and sizes, by automatically broadcasting the smaller array to match the shape of the larger array.

3. Vectorized operations: NumPy provides a set of functions that can be applied to entire arrays or selected elements, without the need for explicit looping.

4. Mathematical functions: NumPy includes a wide range of mathematical functions, including trigonometric, logarithmic, and exponential functions, as well as functions for linear algebra and Fourier analysis.

5. Performance: NumPy is optimized for performance, with most of its functions implemented in C or Fortran, which allows for efficient processing of large amounts of data.

6. Integration with other libraries: NumPy can be easily integrated with other Python libraries, such as Pandas, Matplotlib, and Scikit-learn, which makes it a powerful tool for data analysis and machine learning applications.

### **Qn2**. How do you create a NumPy array using Python's built-in range() function?
### **Ans**.

In [31]:
#loading the package
import numpy as np

# create a range object
my_range = range(10)

# convert the range object to a NumPy array
my_array = np.array(my_range)

# print the NumPy array
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


### **Qn3**. What is the difference between a scalar value and a vector in NumPy?
### **Ans**.
A scalar value is a single numerical value, such as an integer or a floating-point number, that is represented as a 0-dimensional NumPy array. A scalar value can be created using the np.array() function and passing in a single numerical value while a vector is a 1-dimensional array that represents a list of numerical values. A vector can be created using the np.array() function and passing in a list or tuple of numerical values. The main difference between a scalar value and a vector in NumPy is that a scalar is a 0-dimensional array that represents a single numerical value, while a vector is a 1-dimensional array that represents a list of numerical values.

#### Scalar value

In [32]:
# create a scalar value
my_scalar = np.array(5)

# print the scalar value and its shape
print(my_scalar)
print(my_scalar.shape)

5
()


#### Vector

In [33]:
# create a vector
my_vector = np.array([1, 2, 3])

# print the vector and its shape
print(my_vector)
print(my_vector.shape)

[1 2 3]
(3,)


### **Qn4**. How do you calculate the mean of a NumPy array using the mean() function?
### **Ans**.

In [34]:
# create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# To calculate the mean of the array
my_mean = np.mean(my_array)

# print the mean
print(my_mean)

3.0


### **Qn5**. What is broadcasting in NumPy, and how can it be useful?
### **Ans**.
Broadcasting is a powerful feature in NumPy that allows you to perform operations on arrays with different shapes and sizes. Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes by extending or "broadcasting" one or more of the arrays to match the shape of the other array(s) involved in the operation. This means that you can perform arithmetic, logical, and other operations on arrays of different shapes and sizes, without having to manually reshape or duplicate arrays.

Broadcasting follow these basic rules; If the arrays have different numbers of dimensions, the smaller array is broadcasted to the shape of the larger array by adding dimensions of size 1 at the beginning or end of the smaller array, If the arrays have the same number of dimensions, but their sizes do not match along a particular dimension, the array with size 1 is broadcasted along that dimension to match the size of the other array, If the first 2 two rules cant apply, a ValueError is raised.

Broadcasting can be useful in, performing element-wise operations on arrays with different shapes and sizes, adding a scalar value to an array, acaling an array by a scalar value, applying a function to an array element-wise, where the function takes a scalar argument.


##### foreaxmple

In [35]:
# create two arrays with different shapes
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([10, 20, 30])

# add the arrays using broadcasting
z = x + y

# print the result
print(z)

[[11 22 33]
 [14 25 36]]


Here allows us to perform the element-wise addition of x and y, even though they have different shapes. Broadcasting makes it possible to write more concise and readable code, without having to manually reshape or duplicate arrays.

### **Qn6**. How do you create a 2D array in NumPy using Python's built-in list of lists?
### **Ans**. 
Using the **np.array() ** function

In [36]:
# create a list of lists
my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# create a 2D array from the list of lists
my_array = np.array(my_list)

# print the array
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Or

In [39]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### **Qn7**. How can you slice a NumPy array to extract a subarray?
### **Ans**. 
You can slice a NumPy array to extract a subarray using the indexing notation array[start:stop:step], where start is the index of the first element of the subarray, stop is the index of the last element plus one, and step is the stride between the elements. If any of these values are not specified, they default to the following:

--'start': 0

--'stop': size of the corresponding dimension

--'step': 1

##### foreaxmple

In [41]:
#create a 2D array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# extract a subarray using slicing
sub_array = my_array[0:2, 1:3]

# print the subarray
print(sub_array)

[[2 3]
 [5 6]]


### **Qn8**. What are some of the available functions for performing element-wise operations on NumPy arrays?
### **Ans**. 

--'np.add()': element-wise addition of two arrays.

--'np.subtract()': element-wise subtraction of two arrays.

--'np.multiply()': element-wise multiplication of two arrays.

--'np.divide()': element-wise division of two arrays.

--'np.power()': element-wise exponentiation of an array to a given power.

--'np.sqrt()': element-wise square root of an array.

--'np.exp()': element-wise exponential function of an array.

--'np.log()': element-wise natural logarithm of an array.

--'np.abs()': element-wise absolute value of an array.

--'np.sin()': element-wise sine of an array.

### **Qn9**. How do you reshape a NumPy array to have a different shape?
### **Ans**. 
You can reshape a NumPy array to have a different shape using the 'reshape()' function. 

**Syntax-** new_array = old_array.reshape(new_shape)

##### foreaxmple

In [43]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


In [44]:
new_array = my_array.reshape((3, 2))
print(new_array)

[[1 2]
 [3 4]
 [5 6]]


### **Qn10**. How do you perform matrix multiplication on two NumPy arrays using the dot() function?
### **Ans**. 
**Syntax**- result = np.dot(array1, array2)

##### foreaxmple

In [48]:
array1 = np.array([[1, 2], [3, 4], [5, 6]])
array2 = np.array([[7, 8], [9, 10]])
result = np.dot(array1, array2)
print(result)

[[ 25  28]
 [ 57  64]
 [ 89 100]]


In [ ]:
### **Qn11**. How can you use the where() function to apply a condition to a NumPy array?
### **Ans**. 